apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: test
          image: ${REPOSITORY_URI}:latest
          ports:
            - containerPort: 8080